// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecflowPlayground.RegexSamples
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("RegexSamples")]
    public partial class RegexSamplesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RegexSamples.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "RegexSamples", "In order to show off Specflow\nAs a Specflow enthusiast\nI want to demo common rege" +
                    "x for Specflow steps", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Limit argument options to enum values")]
        public virtual void LimitArgumentOptionsToEnumValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Limit argument options to enum values", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product"});
            table1.AddRow(new string[] {
                        "Galaxy IV"});
            table1.AddRow(new string[] {
                        "iPhone"});
            table1.AddRow(new string[] {
                        "Windows Phone"});
            table1.AddRow(new string[] {
                        "Note"});
            table1.AddRow(new string[] {
                        "Kindle"});
#line 7
 testRunner.Given("the following devices", ((string)(null)), table1, "Given ");
#line 14
 testRunner.When("I sort by product name ascending", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product",
                        "Index"});
            table2.AddRow(new string[] {
                        "Galaxy IV",
                        "1"});
            table2.AddRow(new string[] {
                        "iPhone",
                        "2"});
            table2.AddRow(new string[] {
                        "Kindle",
                        "3"});
            table2.AddRow(new string[] {
                        "Note",
                        "4"});
            table2.AddRow(new string[] {
                        "Windows Phone",
                        "5"});
#line 15
 testRunner.Then("they should be in the following order", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Convert 1st, 2nd, etc to integral values")]
        public virtual void Convert1St2NdEtcToIntegralValues()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Convert 1st, 2nd, etc to integral values", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product"});
            table3.AddRow(new string[] {
                        "Galaxy IV"});
            table3.AddRow(new string[] {
                        "iPhone"});
            table3.AddRow(new string[] {
                        "Windows Phone"});
            table3.AddRow(new string[] {
                        "Note"});
            table3.AddRow(new string[] {
                        "Kindle"});
            table3.AddRow(new string[] {
                        "Blackberry Storm"});
            table3.AddRow(new string[] {
                        "iPad"});
            table3.AddRow(new string[] {
                        "Surface"});
            table3.AddRow(new string[] {
                        "Surface Pro"});
            table3.AddRow(new string[] {
                        "HTC One"});
#line 24
 testRunner.Given("the following devices", ((string)(null)), table3, "Given ");
#line 36
 testRunner.When("I remove the 10th item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.And("I remove the 4th item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("I remove the 3rd item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("I remove the 2nd item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I remove the 1st item", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product"});
            table4.AddRow(new string[] {
                        "Kindle"});
            table4.AddRow(new string[] {
                        "Blackberry Storm"});
            table4.AddRow(new string[] {
                        "iPad"});
            table4.AddRow(new string[] {
                        "Surface"});
            table4.AddRow(new string[] {
                        "Surface Pro"});
#line 41
 testRunner.Then("the following devices remain", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Support singular and plural wording")]
        public virtual void SupportSingularAndPluralWording()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Support singular and plural wording", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product"});
            table5.AddRow(new string[] {
                        "Galaxy IV"});
            table5.AddRow(new string[] {
                        "iPhone"});
#line 50
 testRunner.Given("the following devices", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Product"});
            table6.AddRow(new string[] {
                        "Windows Phone"});
#line 54
 testRunner.And("the following device", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
